### ISSUE TITLE
View - Remove Group

### ISSUE THREAD

**Issue by j-sea** [j-sea/skatter#14]
**React Route for:** /remove/group/:id

On Component Mount:
- Axios GET call to: https://bailfire.herokuapp.com/api/group/:id or http://localhost:8080/api/group/:id
    - GET Error prompts the user
    - GET Success loads all of the page with the Group's data

This view contains
---
- Text: Are you sure you want to remove {GROUP_NAME}?
- Buttons
    - No (leads to route: /groups)
    - Axios DELETE call to: https://bailfire.herokuapp.com/api/group/:id or http://localhost:8080/api/group/:id
        - DELETE Error prompts the user
        - DELETE Success leads to route: /groups

**Comment by JandyStephens** [comment]
Tyler making all the buttons
Michelle to stitch them to Axios call
