### ISSUE TITLE
View - Register

### ISSUE THREAD

**Issue by j-sea** [j-sea/skatter#8]
**React Route for:** /register

This view contains
---
- Form fields and corresponding labels for:
    - E-mail
    - Phone
    - Password
- Buttons
    - Back (leads to route: /)
    - Register
        - Axios POST call to: https://bailfire.herokuapp.com/auth/register or http://localhost:8080/auth/register
            - POST Error prompts the user
            - POST Success leads to route: /quickstart

**Comment by msantiago2222** [comment]
done!
