### ISSUE TITLE
View - Sign In

### ISSUE THREAD

**Issue by j-sea** [j-sea/skatter#9]
**React Route for:** /signin

This view contains
---
- Form fields and corresponding labels for:
    - E-mail
    - Phone
    - Password
- Buttons
    - Back (leads to route: /)
    - Sign In
        - Axios POST call to: https://bailfire.herokuapp.com/auth/signin or http://localhost:8080/auth/signin
        - POST Error prompts the user
        - POST Success leads to route: /groups

**Comment by msantiago2222** [comment]
changed LoginForm to SignInForm in index.js and app.js
